version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=atribucion_db
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - DB_URL=postgresql://admin:secret@db:5432/atribucion_db
    depends_on:
      - db
